import React, { useState } from "react";
import type { Recommendation, UnavailableChartReason } from "../types";
import { Sparkles, ArrowRight, Info, AlertCircle } from "lucide-react";

interface RecommendedChartsProps {
  recommendations: Recommendation[];
  unavailable: UnavailableChartReason[];
  onSelectRecommendation: (rec: Recommendation) => void;
}

export const RecommendedCharts: React.FC<RecommendedChartsProps> = ({
  recommendations,
  unavailable,
  onSelectRecommendation,
}) => {
  const [showUnavailable, setShowUnavailable] = useState(false);

  return (
    <div className="card mb-6 p-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4 pb-3 border-b border-[var(--border-color)]">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-amber-400" />
            <h2 className="text-base font-bold text-[var(--text-primary)]">
              Recommended Visualizations ({recommendations.length})
            </h2>
          </div>
          <p className="text-xs text-[var(--text-secondary)] mt-0.5">
            Auto-generated by deterministic field-type decision rules (Zero AI / Zero Hardcoding)
          </p>
        </div>

        <button
          onClick={() => setShowUnavailable(!showUnavailable)}
          className="text-xs text-slate-400 hover:text-blue-400 flex items-center gap-1 cursor-pointer self-start sm:self-auto"
        >
          <Info className="w-3.5 h-3.5" />
          <span>{showUnavailable ? "Hide unavailable charts" : "Why are some charts unavailable?"}</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {recommendations.map((rec) => (
          <div
            key={rec.id}
            className="p-4 bg-[var(--bg-primary)] border border-[var(--border-color)] rounded-xl flex flex-col justify-between hover:border-blue-500 transition group"
          >
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="badge badge-blue text-[11px] uppercase tracking-wider">
                  {rec.chart_type.replace("_", " ")}
                </span>
                {rec.is_top_n_default && (
                  <span className="badge badge-warning text-[10px]">Top {rec.top_n}</span>
                )}
              </div>

              <h3 className="font-bold text-sm text-[var(--text-primary)] mb-1 group-hover:text-blue-400 transition">
                {rec.title}
              </h3>
              <p className="text-xs text-[var(--text-secondary)] mb-3 line-clamp-2">
                {rec.description}
              </p>

              <div className="text-[11px] bg-[var(--bg-card)] p-2 rounded-md mb-3 border border-[var(--border-color)] text-slate-300">
                <div className="font-semibold text-slate-400 mb-0.5">Fields Used:</div>
                <div className="truncate">
                  {Object.entries(rec.fields)
                    .map(([axis, col]) => `${axis.toUpperCase()}: ${col}`)
                    .join(" • ")}
                </div>
              </div>
            </div>

            <button
              onClick={() => onSelectRecommendation(rec)}
              className="w-full py-2 bg-blue-600/10 hover:bg-blue-600 text-blue-400 hover:text-white border border-blue-500/30 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer"
            >
              <span>Customize in Builder</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}
      </div>

      {showUnavailable && (
        <div className="mt-6 pt-4 border-t border-[var(--border-color)]">
          <h4 className="text-xs font-bold text-[var(--text-secondary)] uppercase tracking-wider mb-3">
            Unavailable Chart Types & Guardrail Explanations
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {unavailable.map((item) => (
              <div
                key={item.chart_type}
                className="p-3 bg-[var(--bg-primary)] border border-slate-700/50 rounded-lg text-xs"
              >
                <div className="flex items-center gap-1.5 font-semibold text-slate-300 mb-1">
                  <AlertCircle className="w-3.5 h-3.5 text-amber-500" />
                  <span>{item.title}</span>
                </div>
                <p className="text-[11px] text-[var(--text-secondary)]">{item.reason}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
